  services:

    kafka:
      image: bitnami/kafka:3.6.1
      ports:
        - "9092:9092"
      environment:
        KAFKA_CFG_NODE_ID: 0
        KAFKA_CFG_PROCESS_ROLES: broker,controller
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
        KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_KRAFT_MODE_ENABLED: "true"
        ALLOW_PLAINTEXT_LISTENER: "yes"
        KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true" 


    email-warmup-service:
      build: ./email-warmup-service
      environment:
        PORT: 8080
        KAFKA_BROKERS: kafka:9092
        KAFKA_TOPIC: email-events
        GMAIL_SMTP_USERNAME: abhinitrai1998@gmail.com
        GMAIL_SMTP_APP_PASSWORD: "yesj ahjd ouzl cmin"
        CHOOSEN_SMTP_CLIENT_TYPE: GOOGLE
      ports:
        - "8080:8080"
      depends_on:
       - kafka

    email-health-service:
      build: ./email-health-service
      environment:
        PORT: 8081
        KAFKA_BROKERS: kafka:9092
        KAFKA_TOPIC: email-events
      ports:
        - "8081:8081"
      depends_on:
       - email-warmup-service